"""Initial schema

Revision ID: 5a3535103518
Revises: 
Create Date: 2026-03-21 12:24:52.604996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a3535103518'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('pattern_name', sa.String(length=50), nullable=False),
    sa.Column('win_rate_5d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('win_rate_15d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_gain_5d', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('avg_gain_15d', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=True),
    sa.Column('last_computed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'pattern_name')
    )
    op.create_table('corporate_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_value_cr', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('pattern_name', sa.String(length=50), nullable=False),
    sa.Column('signal_direction', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ohlcv_candles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'timeframe')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('pattern_id', sa.UUID(), nullable=True),
    sa.Column('event_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('win_rate_5d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('win_rate_15d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('high_confluence', sa.Boolean(), nullable=True),
    sa.Column('signal_rank', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('one_liner', sa.String(), nullable=True),
    sa.Column('paragraph_explanation', sa.String(), nullable=True),
    sa.Column('deep_dive', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['detected_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('ohlcv_candles')
    op.drop_table('detected_patterns')
    op.drop_table('corporate_events')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
