"""add unique constraint on signals pattern_id

Revision ID: 9eb927a54c20
Revises: 5a3535103518
Create Date: 2026-03-23 10:05:44.904326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb927a54c20'
down_revision: Union[str, Sequence[str], None] = '5a3535103518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ohlcv_candles_timestamp_idx'), table_name='ohlcv_candles')
    op.create_unique_constraint('uq_signals_pattern_id', 'signals', ['pattern_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_signals_pattern_id', 'signals', type_='unique')
    op.create_index(op.f('ohlcv_candles_timestamp_idx'), 'ohlcv_candles', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
